apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-relay-config
data:
  config.yml: |
    global:
      smtp_host: "0.0.0.0"
      smtp_port: 587
      config_refresh_interval_ms: 300000
      cloudflare_account_id: "YOUR_ACCOUNT_ID"
      cloudflare_api_token: "YOUR_API_TOKEN"
      allowed_from_emails: []
      allowed_to_emails: []
      allowed_from_domains: []
      allowed_to_domains: []

    smtp_users:
      - username: "example_user"
        password: "example_password"
        allowed_from_emails: []
        allowed_to_emails: []
        allowed_from_domains: []
        allowed_to_domains: []
