apiVersion: v1
kind: Service
metadata:
  name: cloudflare-smtp-relay
spec:
  type: LoadBalancer
  selector:
    app: cloudflare-smtp-relay
  ports:
    - protocol: TCP
      port: 587
      targetPort: 587
